-- vim.cmd.colorscheme "kanagawa-dragon"
-- vim.cmd.colorscheme "kanagawa-wave"
-- vim.cmd.colorscheme "melange"
-- vim.cmd.colorscheme "everforest"
-- vim.cmd.colorscheme "catppuccin-mocha"
-- vim.cmd.colorscheme "evergarden"
vim.cmd.colorscheme "vague"